make -s -C IODrivers/HTTPClient/Linux
make -s -C IODrivers/TCPClient/Linux
make -s -C IODrivers/TCPServer/Linux
make -s -C IODrivers/TestFile/Linux
make -s -C IODrivers/TestLoopback/Linux
make -s -C IODrivers/UDPClient/Linux
make -s -C IODrivers/UDPServer/Linux
make -s -C DataProcessors/Highlighter/html/Linux
make -s -C DataProcessors/Highlighter/URLHighlighter/Linux
make -s -C DataProcessors/Other/NewLineProcessor/Linux
