name: Ubuntu 24.04

on:
  release:
    types: [created]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    permissions:
      contents: write 
    name: Build Ubuntu
    runs-on: ubuntu-24.04

    steps:
    - uses: bhowell2/github-substring-action@1.0.2
      id: RelVer
      with:
        value: ${{ github.event.release.tag_name }}
        index_of_str: "Rel_"

    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get install qt6-base-dev qmake6 qt6-tools-dev qt6-base-dev-tools qt6-multimedia-dev fakeroot gzip dpkg

    - name: Build
      working-directory: ./Project
      run: |
        /usr/lib/qt6/bin/qmake WT.pro && make -s

    - name: deb
      working-directory: ./LinuxInstaller
      run: |
        ./MakeRelease.sh ${GITHUB_REF_NAME:4} ../Project 24
        mv WhippyTerm${GITHUB_REF_NAME:4}-1.deb WhippyTerm_${GITHUB_REF_NAME:4}-1_Ubuntu24_04.deb

#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: Upload Release files
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        files: |
          LinuxInstaller/WhippyTerm_${{steps.RelVer.outputs.substring}}-1_Ubuntu24_04.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

